### ISSUE TITLE
verify signatures before confirmation

### ISSUE THREAD

**Issue by johba37** [cosign-io/recovery-js-lib#9]
transaction https://testnet.etherscan.io/tx/0x6bc1926cb34a57a22ae6adb78f92c9cf40712b68dd0d4d77eb5c9dd7713e88e2#eventlog
failed.

there is no reason not to check validity of signatures in node before sending the tx to blockchain and hopping that it works out. would safe cost for failed tx and put more responsibility on developer.

**Comment by johba37** [comment]
error produced on invalid sig:

"rTenant": "0xb77ccd4aef26b0486286d980bde38bc8fa356e98f353a2ebd7d9e518ed4c9d01",
"sTenant": "0xa9c3028b7469a1a3cb7d1e67ef2abc8a66da4d1c58bcfa8f430d818908295fb",

2016-07-18T11:28:27.917Z    bf423ed8-4cda-11e6-bdd2-59fadd0e84a7    TypeError: Invalid hex string at TypeError (native) at Buffer.write (buffer.js:571:21) at fromString (buffer.js:113:26) at new Buffer (buffer.js:58:12) at /var/task/lib/index.js:310:21 at Object.callback (/var/task/node_modules/web3/lib/web3/function.js:118:9) at /var/task/node_modules/web3/lib/web3/method.js:142:25 at /var/task/node_modules/web3/lib/web3/requestmanager.js:89:9 at Web3ProviderEngine._inspectResponseForNewBlock (/var/task/node_modules/web3-provider-engine/index.js:220:12) at /var/task/node_modules/web3-provider-engine/index.js:129:14
